corrections = {
"LLL":"Loma La Lata",
"Lcav":"La Caverna",
"Lach":"La Amarga Chica",
"ADCH":"Aguada del Chañar",
"LaJE":"Laja Este",
"LC":"Loma Campana",
"Soil":"Soil",
"BdtN":"Bajo del Toro Norte",
"ElG":"Entrelagos",
"N":"Narambuena",
"RDMs":"Rincon del Mangrullo Sur",
"RN":"Río Neuquen",
"Adla":"Aguada de la arena",
"ASL":"Al Sur del Lago",
"BS":"Barra de sondeo",
"GR/LT":"gramos por litro",
"S/T":"sin terminar",
"RN":"Rio Neuquén",
"CG":"Cerro Grande",
"LP":"Los Perales",
    }
